name: Integration testing

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  ubuntu-testing:
    name: Test on Windows with MinGW
    runs-on: windows-latest
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v3
      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64
      - name: Build parKVFinder
        run: |
          gcc -v
          make clean
          make
      - name: Integration testing
        run: |
          set KVFinder_PATH=/home/runner/work/parKVFinder-win/parKVFinder-win
          parKVFinder-win64.exe -h
          parKVFinder-win64.exe input/1FMO.pdb
          cat input/KV_Files/1FMO/1FMO.KVFinder.results.toml
          #           bash tests/testing.sh
